version: '2'


services:
  puppetagent:
    container_name: agent
    hostname: agent
    image: puppet/puppet-agent
    ports:
      - 8140
    volumes:
      - ./puppet-agent/puppet.conf:/etc/puppetlabs/puppet/puppet.conf
      - ./data/agent-ssl:/etc/puppetlabs/puppet/ssl/
    networks:
      - default
    command: "agent --verbose --no-daemonize --summarize"

  puppetmaster:
    container_name: puppet
    hostname: puppet
    image: puppet/puppetserver
    ports:
      - "8140:8140"
    volumes:
      - ./code:/etc/puppetlabs/code
      - ./code/hiera.yaml:/etc/puppetlabs/puppet/hiera.yaml
      - ./puppet-master-full/puppet.conf:/etc/puppetlabs/puppet/puppet.conf
      - ./data/server-ssl:/etc/puppetlabs/puppet/ssl/
      - ./data/server-data:/opt/puppetlabs/server/data/puppetserver/
    networks:
      - default

  postgres:
    container_name: puppetpostgres
    hostname: postgres
    image: puppet/puppetdb-postgres
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
    ports:
      - "5432:5432"
    volumes:
      - ./data/progress:/var/lib/postgresql/data/
    networks:
      - default

  puppetdb:
    container_name: puppetdb
    hostname: puppetdb
    image: puppet/puppetdb
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./data/ssl:/etc/puppetlabs/puppet/ssl/
    networks:
      - default

  puppetboard:
    container_name: puppetboard
    hostname: puppetboard
    image: puppet/puppetboard
    ports:
      - "8000:8000"
    networks:
      - default

  puppetexplorer:
    container_name: puppetexplorer
    hostname: puppetexplorer
    image: puppet/puppetexplorer
    ports:
      - "80:80"
    networks:
      - default

networks:
  default:
    driver: bridge
