version: '2'


services:
  puppetagent:
    container_name: agent
    hostname: agent
    image: puppet/puppet-agent
    ports:
      - 8140
    volumes:
      - ./puppet-agent/puppet.conf:/etc/puppetlabs/puppet/puppet.conf
      - ./data/agent-ssl:/etc/puppetlabs/puppet/ssl/
    networks:
      - default
    command: "agent --verbose --no-daemonize --summarize"

  puppetmaster:
    container_name: puppet
    hostname: puppet
    image: puppet/puppetserver-standalone
    ports:
      - "8140:8140"
    volumes:
      - ./code/modules:/etc/puppetlabs/code/environments/production/modules
      - ./code/manifests:/etc/puppetlabs/code/environments/production/manifests
      - ./code/hieradata:/etc/puppetlabs/code/environments/production/hieradata
      - ./code/hiera.yaml:/etc/puppetlabs/puppet/hiera.yaml
      - ./puppet-master/puppet.conf:/etc/puppetlabs/puppet/puppet.conf
      - ./data/server-ssl:/etc/puppetlabs/puppet/ssl/
      - ./data/server-data:/opt/puppetlabs/server/data/puppetserver/
    networks:
      - default

networks:
  default:
    driver: bridge
